---

# Jobs:
# 1. export-installation-before
# 2. upgrade-opsman
# 3. configure-director
# 4. apply-changes
# 5. export-installation-before

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-tasks
  type: s3
  source:
    endpoint: ((s3.endpoint))
    region_name: ((s3.region_name))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    bucket: ((s3.buckets.platform_automation))
    regexp: .*tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    endpoint: ((s3.endpoint))
    region_name: ((s3.region_name))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    bucket: ((s3.buckets.platform_automation))
    regexp: .*image-(.*).tgz

- name: installation-before
  type: s3
  source:
    endpoint: ((s3.endpoint))
    region_name: ((s3.region_name))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    bucket: ((s3.buckets.foundation))
    regexp: installation-before-(.*).zip

- name: installation-after
  type: s3
  source:
    endpoint: ((s3.endpoint))
    region_name: ((s3.region_name))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    bucket: ((s3.buckets.foundation))
    regexp: installation-after-(.*).zip

- name: product
  type: pivnet
  source:
    api_token: ((pivnet.token))
    product_slug: ((product.product_slug))
    product_version: ((product.product_version))
    sort_by: semver

- name: configuration
  type: git
  source:
    private_key: ((git.private_key))
    uri: ((git.configuration.uri))
    branch: master
    username: ((git.user.username))

# reusable stuff
credhub-interpolate: &credhub-interpolate
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: configuration
  params:
    CREDHUB_SERVER: ((credhub.server))
    CREDHUB_CA_CERT: ((credhub.ca_cert))
    CREDHUB_CLIENT: ((credhub.client))
    CREDHUB_SECRET: ((credhub.secret))
    PREFIX: /concourse/((foundation))
    INTERPOLATION_PATH: ((credhub.interpolate_folders))

jobs:
# 1. export-installation-before
- name: export-installation-before
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      trigger: true
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: configuration
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: export-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/vars/env/env.yml
      INSTALLATION_FILE: installation-before-((product.product_slug))-((product.product_version)).zip
  - put: installation-before
    params:
      file: installation/installation-before-((product.product_slug))-((product.product_version)).zip

# 2. upgrade-opsman
- name: upgrade-opsman
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [export-installation-before]
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: product
      params:
        globs:
        - "((product.product_globs))"
    - get: installation-before
    - get: configuration
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: upgrade-opsman
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      image: product
      state: configuration
      config: configuration
      env: interpolated-files
      vars: interpolated-files
      installation: installation-before
    params:
      OPSMAN_CONFIG_FILE: ((foundation))/products/((product.product_slug)).yml
      VARS_FILES: vars/((foundation))/vars/((product.product_slug))-vars.yml
      ENV_FILE: ((foundation))/vars/env/env.yml
      STATE_FILE: ((foundation))/state/state.yml
      INSTALLATION_FILE: installation-before-((product.product_slug))-((product.product_version)).zip
    on_success:
      do:
        - task: make-commit-state
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: configuration
            file-source: generated-state
          output_mapping:
            repository-commit: configuration-commit-state
          params:
            FILE_SOURCE_PATH: state.yml
            FILE_DESTINATION_PATH: ((foundation))/state/state.yml
            GIT_AUTHOR_EMAIL: ((git.user.email))
            GIT_AUTHOR_NAME: ((git.user.username))
            COMMIT_MESSAGE: "Update state file after ((product.product_slug))-((product.product_version))"
        - put: configuration
          params:
            repository: configuration-commit-state
            merge: true
        - task: staged-director-config
          image: platform-automation-image
          file: platform-automation-tasks/tasks/staged-director-config.yml
          input_mapping:
            env: interpolated-files
          params:
            ENV_FILE: ((foundation))/vars/env/env.yml
        - task: make-commit-before
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: configuration
            file-source: generated-config
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: director.yml
            FILE_DESTINATION_PATH: ((foundation))/generated-config/director-((product.product_version)).yml
            GIT_AUTHOR_EMAIL: ((git.user.email))
            GIT_AUTHOR_NAME: ((git.user.username))
            COMMIT_MESSAGE: "Add or update product config: director-((product.product_version)).yml"
        - put: configuration
          params:
            repository: configuration-commit
            merge: true

# 3. configure-director
- name: configure-director
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [upgrade-opsman]
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: configuration
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: configure-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-director.yml
    input_mapping:
      config: configuration
      env: interpolated-files
      vars: interpolated-files
    params:
      ENV_FILE: ((foundation))/vars/env/env.yml
      DIRECTOR_CONFIG_FILE: ((foundation))/products/director.yml
      VARS_FILES: vars/((foundation))/vars/director-vars.yml

# 4. apply-director-changes
- name: apply-director-changes
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      passed: [configure-director]
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: configuration
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/vars/env/env.yml
    on_success:
      do:
        - task: staged-director-config
          image: platform-automation-image
          file: platform-automation-tasks/tasks/staged-director-config.yml
          input_mapping:
            env: interpolated-files
          params:
            ENV_FILE: ((foundation))/vars/env/env.yml
        - task: make-commit-after
          image: platform-automation-image
          file: platform-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: configuration
            file-source: generated-config
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: director.yml
            FILE_DESTINATION_PATH: ((foundation))/generated-config/director-((product.product_version)).yml
            GIT_AUTHOR_EMAIL: ((git.user.email))
            GIT_AUTHOR_NAME: ((git.user.username))
            COMMIT_MESSAGE: "Add or update product config: director-((product.product_version)).yml"
        - put: configuration
          params:
            repository: configuration-commit
            merge: true

# 5 export-installation-after
- name: export-installation-after
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      params: {unpack: true}
      trigger: true
      passed: [apply-director-changes]
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: configuration
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: export-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: ((foundation))/vars/env/env.yml
      INSTALLATION_FILE: installation-after-((product.product_slug))-((product.product_version)).zip
  - put: installation-after
    params:
      file: installation/installation-after-((product.product_slug))-((product.product_version)).zip